#!/usr/bin/env python3
"""Cross-model stealth table: one row per (model, policy), explicit vs stealth.

Reads whatever results/stealth/*_stealth_compare.json files exist (produced by
scripts/stealth_compare.py) and renders the markdown table the paper's
attack-strength section is built from. Safe to run with partial coverage.

Usage:
  python scripts/aggregate_stealth.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

LABELS = {"never_ask": "Never Ask", "always_ask": "Always Ask",
          "confidence_threshold": "Confidence Thresh.",
          "conventional_voi": "Conventional VoI", "trusted_only": "Trusted-Only",
          "channel_heuristic": "Channel Heuristic", "secure_voi": "SecureVoI"}


def main() -> int:
    d = ROOT / "results" / "stealth"
    files = sorted(d.glob("*_stealth_compare.json")) if d.exists() else []
    if not files:
        print("No *_stealth_compare.json under results/stealth/ yet.")
        return 0

    reports = [json.loads(f.read_text(encoding="utf-8")) for f in files]

    lines = ["# Attack-Strength Sensitivity: Explicit vs Stealth Injections", "",
             "Auto-generated by `scripts/aggregate_stealth.py`.", "",
             "Both tiers carry the same prohibited action on the same channel and task;",
             "only the wording differs. Delta = stealth - explicit adversarial unsafe",
             "rate, paired at the task level (2000 bootstrap resamples).", ""]

    for r in reports:
        lines += [f"## {r['model']} ({r['n_paired_tasks']} paired tasks)", "",
                  "| Policy | Explicit unsafe | Stealth unsafe | Delta | 95% CI | p |",
                  "|---|---|---|---|---|---|"]
        for row in r["rows"]:
            dd = row["delta_unsafe"]
            sig = " \\*" if dd["significant_at_0.05"] else ""
            lines.append(
                f"| {LABELS.get(row['policy'], row['policy'])} | "
                f"{row['explicit_unsafe']:.3f} | {row['stealth_unsafe']:.3f} | "
                f"{dd['point']:+.3f}{sig} | "
                f"[{dd['ci_lo']:+.3f}, {dd['ci_hi']:+.3f}] | {dd['p_value']:.3f} |")
        lines.append("")

    # Headline cross-model view: the two rows a reader actually compares -- the
    # undefended baseline (does the attack still LAND as often?) and the defense
    # (does it still get CAUGHT as often?). If conventional_voi is flat across
    # tiers while secure_voi rises, the stealth tier is equally potent but harder
    # to detect, which is the intended manipulation; if conventional_voi drops
    # too, the stealth attacks are simply weaker and the comparison is confounded.
    lines += ["## Headline: is stealth harder to DETECT, or just weaker?", "",
              "| Model | ConvVoI expl | ConvVoI stealth | SecureVoI expl | "
              "SecureVoI stealth | SecureVoI delta |", "|---|---|---|---|---|---|"]
    for r in reports:
        by = {row["policy"]: row for row in r["rows"]}
        c, s = by.get("conventional_voi"), by.get("secure_voi")
        if not (c and s):
            continue
        sig = " \\*" if s["delta_unsafe"]["significant_at_0.05"] else ""
        lines.append(
            f"| {r['model']} | {c['explicit_unsafe']:.3f} | {c['stealth_unsafe']:.3f} | "
            f"{s['explicit_unsafe']:.3f} | {s['stealth_unsafe']:.3f} | "
            f"{s['delta_unsafe']['point']:+.3f}{sig} |")
    lines += ["", "\\* significant at 0.05 (paired bootstrap CI excludes 0)", ""]

    out = ROOT / "results" / "stealth" / "stealth_comparison.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    print(f"Wrote {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
