#!/usr/bin/env python3
"""Cross-model comparison: scan results/models/*/ for completed runs and
render one table comparing them side by side -- SecureVoI vs Conventional
VoI's adversarial unsafe rate, benign utility, and (where available) the
oracle-ablation gap and guardrail comparison, per model.

Run any time; picks up whatever models have finished so far (partial
coverage is fine, this is meant to be re-run as more models land, including
mid-session while others are still in flight).

Usage:
  python scripts/aggregate_models.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parents[1]


def load_json(path: Path):
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def main() -> int:
    models_dir = ROOT / "results" / "models"
    rows = []

    # Include the repo-default results/ (currently Mistral-Nemo-12B, per
    # Anagh's run) as its own row alongside anything under results/models/.
    candidates = [("(default) results/", ROOT / "results")]
    if models_dir.exists():
        candidates += [(d.name, d) for d in sorted(models_dir.iterdir()) if d.is_dir()]

    seen_backends = set()
    for label, d in candidates:
        primary = load_json(d / "primary_summary.json")
        if primary is None:
            continue
        backend = primary.get("agent_backend")
        if backend in seen_backends:
            continue  # same run archived under two paths (e.g. results/ AND results/models/<name>/)
        seen_backends.add(backend)
        stats = load_json(d / "stats.json")
        oracle = load_json(d / "oracle_ablation.json")
        guardrail = load_json(d / "guardrail_eval.json")
        table = primary.get("table", {})
        conv_adv = table.get("conventional_voi|adversarial", {})
        secure_adv = table.get("secure_voi|adversarial", {})
        secure_benign = table.get("secure_voi|benign", {})
        trusted_benign = table.get("trusted_only|benign", {})

        row = {
            "model": primary.get("agent_backend", label),
            "n_test_tasks": primary.get("n_test_tasks"),
            "verdict": primary.get("verdict"),
            "conv_adv_unsafe": conv_adv.get("unsafe_rate"),
            "secure_adv_unsafe": secure_adv.get("unsafe_rate"),
            "secure_benign_util": secure_benign.get("utility"),
            "trusted_benign_util": trusted_benign.get("utility"),
        }
        if oracle:
            row["oracle_gap"] = oracle.get("remaining_unsafe_rate_gap_to_oracle")
        if guardrail:
            gtable = guardrail.get("table", {})
            row["guardrail_adv_unsafe"] = gtable.get("post_hoc_guardrail|adversarial", {}).get("unsafe_rate")
            row["guardrail_adv_goal"] = gtable.get("post_hoc_guardrail|adversarial", {}).get("goal_rate")
        rows.append(row)

    if not rows:
        print("No completed model runs found under results/ or results/models/*/ yet.")
        return 0

    lines = ["# Cross-Model Comparison", "", "Auto-generated by `scripts/aggregate_models.py` "
            "-- re-run any time more models complete.", "",
            "| Model | n_test | Verdict | ConvVoI adv unsafe | SecureVoI adv unsafe | "
            "SecureVoI benign util | Trusted-Only benign util | Oracle gap | Guardrail adv unsafe | Guardrail adv goal |",
            "|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        def fmt(k, prec=3):
            v = r.get(k)
            return f"{v:.{prec}f}" if isinstance(v, (int, float)) else "—"
        lines.append(
            f"| {r['model']} | {r.get('n_test_tasks','—')} | {r.get('verdict','—')} | "
            f"{fmt('conv_adv_unsafe')} | {fmt('secure_adv_unsafe')} | {fmt('secure_benign_util')} | "
            f"{fmt('trusted_benign_util')} | {fmt('oracle_gap')} | {fmt('guardrail_adv_unsafe')} | "
            f"{fmt('guardrail_adv_goal')} |"
        )

    out_path = ROOT / "results" / "cross_model_comparison.md"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    print(f"\nWrote {out_path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
