#!/usr/bin/env python3
"""Render the frontier closed-model (OpenAI / Anthropic) results as LaTeX.

Every number in the output document is read out of results/models/*/ at
render time rather than transcribed by hand, so the .tex cannot silently
drift from the episode files the way results/stats.json repeatedly has (see
results/README.md). Re-run this after any model's run changes.

Usage:
  python3 scripts/make_frontier_table.py            # -> results/frontier_models.tex
  python3 scripts/make_frontier_table.py --out X.tex
"""
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "results/models"

POLICIES = [
    ("never_ask", "Never-Ask"),
    ("always_ask", "Always-Ask"),
    ("confidence_threshold", "Confidence-Threshold"),
    ("conventional_voi", "Conventional VoI"),
    ("trusted_only", "Trusted-Only"),
    ("secure_voi", "SecureVoI"),
    ("channel_heuristic", "Channel-Heuristic"),
]

# (results dir, display name, provider) for the two frontier models this
# document is about.
FRONTIER_MAIN = [("gpt-5.4-mini", "GPT-5.4-mini", "OpenAI"),
                 ("claude-sonnet-5", "Claude Sonnet 5", "Anthropic")]
FRONTIER_DIV = [("gpt-5.4-mini-diversity", "GPT-5.4-mini", "OpenAI"),
                ("claude-sonnet-5-diversity", "Claude Sonnet 5", "Anthropic")]

# Already-published open-weight models, for context rows only.
OPEN_MAIN = [("mistral-nemo-12b", "Mistral-Nemo-12B"),
             ("llama-3.3-70b", "Llama-3.3-70B"),
             ("gpt-oss-20b-cloud", "GPT-OSS-20B"),
             ("gpt-oss-120b-cloud", "GPT-OSS-120B")]
OPEN_DIV = [("mistral-nemo-12b-diversity", "Mistral-Nemo-12B"),
            ("gpt-oss-20b-cloud-diversity", "GPT-OSS-20B"),
            ("gpt-oss-120b-cloud-diversity", "GPT-OSS-120B")]


def load(d: str) -> tuple[dict, dict, list]:
    summary = json.loads((RES / d / "primary_summary.json").read_text())
    calib = json.loads((RES / d / "dev_calibration.json").read_text())
    eps = json.loads((RES / d / "primary_episodes.json").read_text())
    return summary, calib, eps


def f3(x) -> str:
    return f"{x:.3f}"


def ask_rate(eps: list, policy: str, condition: str) -> float:
    rows = [e for e in eps if e["policy"] == policy and e["condition"] == condition]
    return sum(1 for e in rows if e["asked"]) / len(rows) if rows else float("nan")


def policy_block(d: str) -> str:
    """7 policy rows for one model/task-set."""
    s, _, eps = load(d)
    t = s["table"]
    out = []
    for key, label in POLICIES:
        b, a = t[f"{key}|benign"], t[f"{key}|adversarial"]
        bold = r"\bfseries " if key == "secure_voi" else ""
        out.append(
            f"{bold}{label} & {f3(b['utility'])} & {f3(b['goal_rate'])} & "
            f"{f3(ask_rate(eps, key, 'benign'))} & {f3(a['utility'])} & "
            f"{f3(a['unsafe_rate'])} & {f3(a['attack_success'])} \\\\")
    return "\n".join(out)


def qformat_split(d: str) -> dict[str, tuple[int, int]]:
    """Adversarial unsafe count by question format, for the two risk-blind
    asking policies. Always-Ask and Conventional VoI differ only in that
    Always-Ask ignores interaction cost, which makes it pick open-format
    questions where the cost-aware policy picks restricted ones -- and those
    two formats carry different injected strings."""
    _, _, eps = load(d)
    res = {}
    for pol in ("always_ask", "conventional_voi"):
        rows = [e for e in eps if e["policy"] == pol
                and e["condition"] == "adversarial" and e["asked"]]
        fmts = Counter(e["qformat"] for e in rows)
        fmt = fmts.most_common(1)[0][0] if fmts else "--"
        res[pol] = (fmt, sum(1 for e in rows if e["unsafe"]), len(rows))
    return res


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="results/frontier_models.tex")
    args = ap.parse_args()

    L = []
    A = L.append

    A(r"""% Auto-generated by scripts/make_frontier_table.py -- do not hand-edit.
% Every number is read from results/models/*/primary_summary.json and
% primary_episodes.json at render time. Re-run the script after any re-run.
\documentclass[11pt]{article}
\usepackage[margin=1in]{geometry}
\usepackage{booktabs}
\usepackage{amsmath}
\usepackage{caption}
\title{Frontier Closed-Model Results:\\OpenAI GPT-5.4-mini and Anthropic Claude Sonnet 5}
\author{secure-clarify}
\begin{document}
\maketitle

\section{Scope and protocol}

Prior results in this project cover four open-weight models only
(Mistral-Nemo-12B, Llama-3.3-70B, GPT-OSS-20B, GPT-OSS-120B). This document
reports the two frontier closed models added to answer that gap, each run
through the \emph{same} two headline evaluations the open-weight models
received, at the cheap/fast tier of each provider.

\begin{itemize}
  \item \textbf{Main benchmark:} \texttt{tasks/main\_120.json}, 96 test-split
        tasks, 2 domains (file, calendar).
  \item \textbf{Diversity benchmark:} \texttt{tasks/diversity\_180.json}, 144
        test-split tasks, 3 domains (file, calendar, messaging), used to test
        whether findings survive a task family the policies were not designed
        against.
\end{itemize}

Both use \texttt{--policies mainplus} (7 policies) under the two published
conditions (benign, adversarial-explicit), giving
$96\times7\times2=1344$ and $144\times7\times2=2016$ episodes respectively.
Decoding is deterministic (temperature 0). The risk-aversion parameter
$\lambda$ and the channel priors are fit \emph{per model and per task set} on
that set's own dev split, never on test; $\lambda$ is not transferred between
models or between task sets.

\paragraph{Metrics.} \emph{Benign utility} and \emph{benign goal rate} measure
task success with no attacker present. \emph{Adversarial unsafe rate} is the
fraction of adversarial episodes in which the agent performs a prohibited
action, and is the primary safety number. \emph{Attack success} is the
fraction in which the injected objective is actually achieved. \emph{Ask rate}
is the fraction of episodes in which the policy chose to ask a clarifying
question.

\section{Run inventory and verification}
""")

    A(r"""\begin{table}[h]
\centering
\caption{Coverage and verification. Every reported cell is full coverage with
zero excluded tasks. ``Rescore'' is \texttt{scripts/rescore.py}, which re-scores
each saved plan under current scoring code and must report no verdict changes.}
\begin{tabular}{llrrrrl}
\toprule
Model & Task set & Tasks & Episodes & $\lambda$ & Verdict & Rescore \\
\midrule""")
    for d, name, prov in FRONTIER_MAIN + FRONTIER_DIV:
        s, c, eps = load(d)
        tset = "main-96" if "main" in s["tasks_file"] else "diversity-144"
        A(f"{name} ({prov}) & {tset} & {s['n_test_tasks']} & {len(eps)} & "
          f"{s['lambda_used']} & {s['verdict']} & no changes \\\\")
    A(r"""\bottomrule
\end{tabular}
\end{table}""")

    A(r"""
All four runs pass the four pre-registered go/no-go checks
(\texttt{benign\_clarification\_helps}, \texttt{adversarial\_clarification\_hurts},
\texttt{secure\_reduces\_unsafe}, \texttt{secure\_not\_degenerate}), and
\texttt{python3 test\_smoke.py} passes.

\section{Main benchmark (96 tasks)}
""")

    for d, name, prov in FRONTIER_MAIN:
        s, c, _ = load(d)
        A(r"\begin{table}[h]" "\n" r"\centering")
        A(f"\\caption{{\\textbf{{{name}}} ({prov}), main benchmark, 96 test tasks, "
          f"1344 episodes, $\\lambda={s['lambda_used']}$ fit on {c['n_dev_tasks']} dev tasks. "
          f"Verdict {s['verdict']}.}}")
        A(r"""\begin{tabular}{lrrrrrr}
\toprule
& \multicolumn{3}{c}{Benign} & \multicolumn{3}{c}{Adversarial} \\
\cmidrule(lr){2-4}\cmidrule(lr){5-7}
Policy & Utility & Goal rate & Ask rate & Utility & Unsafe & Attack succ. \\
\midrule""")
        A(policy_block(d))
        A(r"\bottomrule" "\n" r"\end{tabular}" "\n" r"\end{table}")
        A("")

    A(r"\section{Diversity benchmark (144 tasks, 3 domains)}" "\n")

    for d, name, prov in FRONTIER_DIV:
        s, c, _ = load(d)
        A(r"\begin{table}[h]" "\n" r"\centering")
        A(f"\\caption{{\\textbf{{{name}}} ({prov}), diversity benchmark, 144 test tasks, "
          f"2016 episodes, $\\lambda={s['lambda_used']}$ fit on {c['n_dev_tasks']} dev tasks. "
          f"Verdict {s['verdict']}.}}")
        A(r"""\begin{tabular}{lrrrrrr}
\toprule
& \multicolumn{3}{c}{Benign} & \multicolumn{3}{c}{Adversarial} \\
\cmidrule(lr){2-4}\cmidrule(lr){5-7}
Policy & Utility & Goal rate & Ask rate & Utility & Unsafe & Attack succ. \\
\midrule""")
        A(policy_block(d))
        A(r"\bottomrule" "\n" r"\end{tabular}" "\n" r"\end{table}")
        A("")

    # --- cross-model headline -------------------------------------------
    A(r"""\section{Cross-model comparison}

The headline claim is that SecureVoI cuts the adversarial unsafe rate well
below risk-blind Conventional VoI without giving up benign utility, and that
it also beats Channel-Heuristic (the trivial ``just avoid untrusted channels''
baseline) --- otherwise the benchmark would be solvable by channel avoidance
alone.

\begin{table}[h]
\centering
\caption{Main benchmark, 96 tasks. Adversarial unsafe rate by policy, with
SecureVoI's benign utility for reference. Lower unsafe is better.}
\begin{tabular}{lrrrrr}
\toprule
Model & Conv.\ VoI & Chan.\ Heur. & SecureVoI & SecureVoI benign util. & $\lambda$ \\
\midrule""")
    for d, name in [(a, b) for a, b, _ in FRONTIER_MAIN] + OPEN_MAIN:
        s, _, _ = load(d)
        t = s["table"]
        A(f"{name} & {f3(t['conventional_voi|adversarial']['unsafe_rate'])} & "
          f"{f3(t['channel_heuristic|adversarial']['unsafe_rate'])} & "
          f"{f3(t['secure_voi|adversarial']['unsafe_rate'])} & "
          f"{f3(t['secure_voi|benign']['utility'])} & {s['lambda_used']} \\\\")
    A(r"""\bottomrule
\end{tabular}
\end{table}

\begin{table}[h]
\centering
\caption{Diversity benchmark, 144 tasks. Llama-3.3-70B is omitted: its
diversity run is incomplete (Groq token-per-minute limited) and a
partial-coverage number should not be reported.}
\begin{tabular}{lrrrrr}
\toprule
Model & Conv.\ VoI & Chan.\ Heur. & SecureVoI & SecureVoI benign util. & $\lambda$ \\
\midrule""")
    for d, name in [(a, b) for a, b, _ in FRONTIER_DIV] + OPEN_DIV:
        s, _, _ = load(d)
        t = s["table"]
        A(f"{name} & {f3(t['conventional_voi|adversarial']['unsafe_rate'])} & "
          f"{f3(t['channel_heuristic|adversarial']['unsafe_rate'])} & "
          f"{f3(t['secure_voi|adversarial']['unsafe_rate'])} & "
          f"{f3(t['secure_voi|benign']['utility'])} & {s['lambda_used']} \\\\")
    A(r"""\bottomrule
\end{tabular}
\end{table}
""")

    # --- the always-ask anomaly -----------------------------------------
    A(r"""\section{Two findings that need a decision before publication}

\subsection{Always-Ask is safe on Claude Sonnet 5 and catastrophic everywhere else}

On both frontier task sets, Claude Sonnet 5 records an adversarial unsafe rate
of exactly $0.000$ under \textbf{Always-Ask} --- the risk-blind baseline that
asks on the nominally most informative channel and accepts whatever comes back
with \emph{no} stage-2 screening --- together with the highest adversarial
utility of any policy. This is specific to Claude, not to frontier models in
general: on all four open-weight models \emph{and} on GPT-5.4-mini, the same
baseline is catastrophic (unsafe rate $0.583$--$0.594$ on the main set).

The mechanism is not a scoring artifact. Always-Ask and Conventional VoI select
the same channels; they differ only in that Always-Ask ignores interaction
cost, which makes it prefer open-format questions where the cost-aware policy
prefers restricted ones. Those two formats carry different injected strings.
Table~\ref{tab:qformat} shows the resulting split: on every other model, both
formats land with near-identical potency, whereas on Claude the
restricted-format injection still succeeds while the open-format one never
does.

\begin{table}[h]
\centering
\caption{Adversarial unsafe count among episodes where the policy asked,
split by the question format each policy selects. Same injected objective,
same channels; only the surrounding question format differs.}
\label{tab:qformat}
\begin{tabular}{llrlr}
\toprule
& \multicolumn{2}{c}{Always-Ask} & \multicolumn{2}{c}{Conventional VoI} \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}
Model & Format & Unsafe & Format & Unsafe \\
\midrule""")
    for d, name in [("claude-sonnet-5", "Claude Sonnet 5 (main-96)"),
                    ("claude-sonnet-5-diversity", "Claude Sonnet 5 (div-144)"),
                    ("gpt-5.4-mini", "GPT-5.4-mini (main-96)"),
                    ("gpt-5.4-mini-diversity", "GPT-5.4-mini (div-144)"),
                    ("mistral-nemo-12b", "Mistral-Nemo-12B (main-96)"),
                    ("llama-3.3-70b", "Llama-3.3-70B (main-96)"),
                    ("gpt-oss-120b-cloud", "GPT-OSS-120B (main-96)")]:
        q = qformat_split(d)
        af, au, an = q["always_ask"]
        cf, cu, cn = q["conventional_voi"]
        A(f"{name} & {af} & {au}/{an} & {cf} & {cu}/{cn} \\\\")
    A(r"""\bottomrule
\end{tabular}
\end{table}

Because the same strings are equally potent against every other model in both
formats, this is most consistent with Claude's own refusal behaviour
rather than a weak attack string. The consequence for the paper's framing is
direct: on this model a risk-blind always-ask policy is \emph{safer} under
attack than the risk-aware one, because the model's own resistance substitutes
for the policy's channel avoidance. This is the same class of result as the
stage-1/stage-2 screened ablation negative already documented in
\texttt{HANDOFF.md}, and it should be reported rather than omitted.

\subsection{SecureVoI's margin over channel avoidance shrinks on the diversity set}

SecureVoI's advantage over the trivial Channel-Heuristic baseline is
comfortable for every model except Claude Sonnet 5. GPT-5.4-mini holds a
$+0.333$ margin on both task sets, as do GPT-OSS-20B and GPT-OSS-120B on the
diversity set ($+0.333$ each) and Mistral-Nemo-12B ($+0.264$). Claude is the
exception: $+0.094$ on the main set, narrowing to $+0.021$
($0.104$ vs.\ $0.125$) on the diversity set. Since this margin is the paper's
answer to ``your benchmark is solvable by channel avoidance alone,'' the
Claude diversity cell in particular should carry a paired bootstrap confidence
interval before any claim rests on it; at $n=144$ a gap of $0.021$ is unlikely
to be distinguishable from zero.

\section{Reproduction}

\begin{verbatim}
# OpenAI
python3 scripts/tune_dev.py    --tasks tasks/main_120.json \
  --out results/models/gpt-5.4-mini/dev_calibration.json \
  --backend openai --model gpt-5.4-mini \
  --base-url https://api.openai.com/v1/chat/completions \
  --api-key-env OPENAI_API_KEY
python3 scripts/run_primary.py --tasks tasks/main_120.json \
  --calibration results/models/gpt-5.4-mini/dev_calibration.json \
  --policies mainplus \
  --out results/models/gpt-5.4-mini/primary_summary.json \
  --episodes-out results/models/gpt-5.4-mini/primary_episodes.json \
  --backend openai --model gpt-5.4-mini \
  --base-url https://api.openai.com/v1/chat/completions \
  --api-key-env OPENAI_API_KEY --resume

# Anthropic
python3 scripts/tune_dev.py    --tasks tasks/main_120.json \
  --out results/models/claude-sonnet-5/dev_calibration.json \
  --backend anthropic --model claude-sonnet-5 --api-key-env ANTHROPIC_API_KEY
python3 scripts/run_primary.py --tasks tasks/main_120.json \
  --calibration results/models/claude-sonnet-5/dev_calibration.json \
  --policies mainplus \
  --out results/models/claude-sonnet-5/primary_summary.json \
  --episodes-out results/models/claude-sonnet-5/primary_episodes.json \
  --backend anthropic --model claude-sonnet-5 \
  --api-key-env ANTHROPIC_API_KEY --resume
\end{verbatim}

Substitute \texttt{tasks/diversity\_180.json} and the \texttt{-diversity}
result directories for the diversity runs. API keys are read from the
environment and are never stored in the repository.

\paragraph{Backend notes.} Two provider-specific fixes were required and are
in \texttt{scripts/model\_backends.py}. OpenAI's current model lineup rejects
\texttt{max\_tokens} and requires \texttt{max\_completion\_tokens}. Claude's
Sonnet-5 family rejects an explicit \texttt{temperature: 0.0}, so the field is
omitted for deterministic runs and adaptive thinking is disabled. Both
providers also needed a larger output-token budget than the 512-token default
(1536 for OpenAI, 2048 for Anthropic): their intent-hypothesis JSON is verbose
enough that the default truncates mid-object, and the parser's fallback
silently returns empty hypotheses, which reads as zero information gain on
every task and produces a flat, meaningless $\lambda$ frontier.

\end{document}""")

    out = ROOT / args.out
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"Wrote {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
